# Generated by Django 4.2.13 on 2024-06-07 11:58

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('post_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
