# Generated by Django 4.2.13 on 2024-06-09 13:43

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('post_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
